stages:
  - test
  - coverage
  - build
  - documentation

variables:
  AWS_DEFAULT_REGION: us-east-1
  OPS_ACCOUNT_ID: 468665244580
  PROB_FORECASTING_ACCOUNT_ID: 052722095006
  JULIA_GITLAB_CI_IMAGE: ${OPS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/julia-gitlab-ci:0.6
  JULIA_BAKED_IMAGE: ${OPS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/julia-baked:0.6
  GP_IMAGE: ${PROB_FORECASTING_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/gpforecasting/gpforecasting:${CI_COMMIT_REF_SLUG}

.test_docker: &test_docker
  artifacts:
    name: coverage
    expire_in: 1 week
    paths:
      - "$CI_JOB_NAME coverage/"
  script:
    - export PYTHON=""  # Configure PyCall to use the Conda.jl package's Python
    - julia --compilecache=no -e "Pkg.clone(pwd()); Pkg.build(\"$PKG_NAME\"); Pkg.test(\"$PKG_NAME\"; coverage=true)"
    - julia-coverage $PKG_NAME

.test_docker_0_6: &test_docker_0_6
  image: $JULIA_GITLAB_CI_IMAGE
  <<: *test_docker


"0.6 (Linux, 64-bit, Docker)":
  tags:
    - docker-ci
    - linux
    - 64-bit
  <<: *test_docker_0_6

"Coverage":
  stage: coverage
  image: $JULIA_GITLAB_CI_IMAGE
  coverage: /Test Coverage (\d+\.\d+%)/
  artifacts:
    name: combined_coverage
    expire_in: 1 week
    paths:
      - combined_coverage/
  tags:
    - linux
    - docker-ci
  before_script:
    - curl -s -o julia-ci https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/julia-ci
    - chmod +x julia-ci
  script:
    - ./julia-ci publish-coverage combined_coverage
  after_script:
    - ./julia-ci clean

"Docker Build":
  stage: build
  tags:
    - docker-build
  only:
    - master
    - develop
    - docs
    - tags  # special keyword for all tags
  script:
    - aws ecr get-login --no-include-email --registry-ids $OPS_ACCOUNT_ID $PROB_FORECASTING_ACCOUNT_ID | eval $SHELL
    - docker pull $JULIA_BAKED_IMAGE
    - docker tag $JULIA_BAKED_IMAGE julia-baked:0.6
    - docker build --no-cache -t $GP_IMAGE .
    - docker push $GP_IMAGE
  after_script:
    - docker rmi $GP_IMAGE
    - docker rmi $JULIA_BAKED_IMAGE
    - docker rmi julia-baked:0.6

"Documentation":
  stage: documentation
  tags:
    - docs
    - shell-ci
  only:
    - master
    - develop
    - docs
    - tags  # special keyword for all tags
  variables:
    JULIA_VERSION: "0.6"
  before_script:
    - curl -s -o julia-ci https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/julia-ci
    - chmod +x julia-ci
    - ./julia-ci install $JULIA_VERSION
  script:
    - source julia-ci export
    - ./julia-ci docs
  after_script:
    - ./julia-ci clean
