stages:
  - test
  - teardown

include:
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/templates/hidden-jobs.yml
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/templates/teardown.yml

# Do not test on 32-bit machines becuase of the memory requirements of this package
# https://gitlab.invenia.ca/research/GPForecasting.jl/issues/31
"1.0 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_1_0

"1.0 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_1_0

"1.1 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_1_1

"1.1 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_1_1

"Nightly (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_nightly

"Nightly (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_nightly

.test_docker_build: &test_docker_build
  tags:
    - docker-build
  variables:
    OPS_ACCOUNT_ID: 468665244580
    JULIA_IMAGE: ${OPS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/julia-gitlab-ci:1.0.3  # for coverage and test_docker
    JULIA_BAKED_IMAGE: ${OPS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/julia-baked:1.0.3
    PROB_FORECASTING_ACCOUNT_ID: 052722095006
    GP_IMAGE: ${PROB_FORECASTING_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/gpforecasting/gpforecasting:${CI_COMMIT_REF_SLUG}
  script:
    - aws ecr get-login --no-include-email --registry-ids $OPS_ACCOUNT_ID $PROB_FORECASTING_ACCOUNT_ID | eval $SHELL
    - docker pull $JULIA_BAKED_IMAGE
    - docker tag $JULIA_BAKED_IMAGE julia-baked:1.0.3
    - docker build --no-cache -t $GP_IMAGE .
    - docker push $GP_IMAGE
  after_script:
    - docker rmi $GP_IMAGE
    - docker rmi -f $JULIA_BAKED_IMAGE

"Docker Build":
  stage: teardown
  only:
    - master
    - tags  # special keyword for all tags
  <<: *test_docker_build

"Docker Build":
  stage: teardown
  when: manual
  <<: *test_docker_build
